USE DATABASE "LENDING_CLUB";
USE SCHEMA "PUBLIC";

-- Fact Table
CREATE TABLE PUBLIC."ACCEPTED" (
    "id" INTEGER NOT NULL PRIMARY KEY,
    "member_id" nvarchar(31) NOT NULL,
    "loan_amnt" FLOAT NOT NULL,
    "funded_amnt" FLOAT NOT NULL,
    "funded_amnt_inv" FLOAT NOT NULL,
    "term" INTEGER NOT NULL,
    "int_rate" FLOAT NOT NULL,
    "installment" FLOAT NOT NULL,
    "grade" nvarchar(1) NOT NULL,
    "sub_grade" nvarchar(2) NOT NULL,
    "emp_title" TEXT,
    "emp_length" INT NOT NULL,
    "home_ownership" nvarchar(31) NOT NULL,
    "annual_inc" FLOAT NOT NULL,
    "verification_status" nvarchar(31) NOT NULL,
    "issue_d" TIMESTAMP NOT NULL,
    "loan_status" nvarchar(31) NOT NULL,
    "pymnt_plan" TEXT NOT NULL,
    "url" TEXT,
    "desc" nvarchar(255),
    "purpose" nvarchar(31) ,
    "title" nvarchar(31) ,
    "zip_code" INT NOT NULL,
    "addr_state" nvarchar(2)  NOT NULL,
    "dti" FLOAT NOT NULL,
    "delinq_2yrs" FLOAT,
    "earliest_cr_line" TIMESTAMP NOT NULL,
    "fico_range_low" NUMBER(8,0) NOT NULL,
    "fico_range_high" NUMBER(8,0) NOT NULL,
    "inq_last_6mths" NUMBER(8,0),
    "mths_since_last_delinq" NUMBER(8,0),
    "mths_since_last_record" NUMBER(8,0),
    "open_acc" NUMBER(8,0),
    "pub_rec" NUMBER(8,0),
    "revol_bal" FLOAT,
    "revol_util" FLOAT,
    "total_acc" NUMBER(8,0),
    "initial_list_status" nvarchar(32),
    "out_prncp" FLOAT,
    "out_prncp_inv" FLOAT,
    "total_pymnt" FLOAT NOT NULL,
    "total_pymnt_inv" FLOAT NOT NULL,
    "total_rec_prncp" FLOAT NOT NULL,
    "total_rec_int" FLOAT NOT NULL,
    "total_rec_late_fee" FLOAT NOT NULL,
    "recoveries" FLOAT NOT NULL,
    "collection_recovery_fee" FLOAT NOT NULL,
    "last_pymnt_d" TIMESTAMP NOT NULL,
    "last_pymnt_amnt" FLOAT,
    "next_pymnt_d" TEXT,
    "last_credit_pull_d" TEXT,
    "last_fico_range_high" FLOAT,
    "last_fico_range_low" FLOAT,
    "collections_12_mths_ex_med" FLOAT,
    "mths_since_last_major_derog" FLOAT,
    "policy_code" FLOAT,
    "application_type" TEXT NOT NULL,
    "annual_inc_joint" FLOAT,
    "dti_joint" FLOAT,
    "verification_status_joint" TEXT,
    "acc_now_delinq" FLOAT,
    "tot_coll_amt" FLOAT,
    "tot_cur_bal" FLOAT,
    "open_acc_6m" NUMBER(8,0),
    "open_act_il" NUMBER(8,0),
    "open_il_12m" NUMBER(8,0),
    "open_il_24m" NUMBER(8,0),
    "mths_since_rcnt_il" NUMBER(8,0),
    "total_bal_il" FLOAT,
    "il_util" FLOAT,
    "open_rv_12m" FLOAT,
    "open_rv_24m" FLOAT,
    "max_bal_bc" FLOAT,
    "all_util" FLOAT,
    "total_rev_hi_lim" FLOAT,
    "inq_fi" FLOAT,
    "total_cu_tl" FLOAT,
    "inq_last_12m" FLOAT,
    "acc_open_past_24mths" FLOAT,
    "avg_cur_bal" FLOAT,
    "bc_open_to_buy" FLOAT,
    "bc_util" FLOAT,
    "chargeoff_within_12_mths" FLOAT,
    "delinq_amnt" FLOAT,
    "mo_sin_old_il_acct" NUMBER(8,0),
    "mo_sin_old_rev_tl_op" NUMBER(8,0),
    "mo_sin_rcnt_rev_tl_op" NUMBER(8,0),
    "mo_sin_rcnt_tl" NUMBER(8,0),
    "mort_acc" FLOAT,
    "mths_since_recent_bc" NUMBER(8,0),
    "mths_since_recent_bc_dlq" NUMBER(8,0),
    "mths_since_recent_inq" NUMBER(8,0),
    "mths_since_recent_revol_delinq" NUMBER(8,0),
    "num_accts_ever_120_pd" NUMBER(8,0),
    "num_actv_bc_tl" NUMBER(8,0),
    "num_actv_rev_tl" NUMBER(8,0),
    "num_bc_sats" NUMBER(8,0),
    "num_bc_tl" NUMBER(8,0),
    "num_il_tl" NUMBER(8,0),
    "num_op_rev_tl" NUMBER(8,0),
    "num_rev_accts" NUMBER(8,0),
    "num_rev_tl_bal_gt_0" NUMBER(8,0),
    "num_sats" NUMBER(8,0),
    "num_tl_120dpd_2m" NUMBER(8,0),
    "num_tl_30dpd" NUMBER(8,0),
    "num_tl_90g_dpd_24m" NUMBER(8,0),
    "num_tl_op_past_12m" NUMBER(8,0),
    "pct_tl_nvr_dlq" FLOAT,
    "percent_bc_gt_75" FLOAT,
    "pub_rec_bankruptcies" NUMBER(8,0),
    "tax_liens" NUMBER(8,0),
    "tot_hi_cred_lim" FLOAT,
    "total_bal_ex_mort" FLOAT,
    "total_bc_limit" FLOAT,
    "total_il_high_credit_limit" FLOAT,
    "revol_bal_joint" FLOAT,
    "sec_app_fico_range_low" NUMBER(8,0),
    "sec_app_fico_range_high" NUMBER(8,0),
    "sec_app_earliest_cr_line" TIMESTAMP,
    "sec_app_inq_last_6mths" NUMBER(8,0),
    "sec_app_mort_acc" NUMBER(8,0),
    "sec_app_open_acc" NUMBER(8,0),
    "sec_app_revol_util" FLOAT,
    "sec_app_open_act_il" FLOAT,
    "sec_app_num_rev_accts" FLOAT,
    "sec_app_chargeoff_within_12_mths" NUMBER(8,0),
    "sec_app_collections_12_mths_ex_med" NUMBER(8,0),
    "sec_app_mths_since_last_major_derog" NUMBER(8,0),
    "disbursement_method" TEXT,
    "hardship_flag" BOOLEAN NOT NULL,
    "debt_settlement_flag" BOOLEAN,
    "created_on" TIMESTAMP,
    "last_updated" TIMESTAMP,
    "warehouse_created_on" TIMESTAMP DEFAULT current_timestamp(),
    "warehouse_last_updated" TIMESTAMP DEFAULT current_timestamp()
    -- If there was a Member's Profile table, we would link it here
    -- CONSTRAINT members_fk
    --     FOREIGN KEY("member_id") 
    --     REFERENCES "members"("id"),
);


-- Dimension Tables
CREATE TABLE PUBLIC."HARDSHIP" (
    "loan_id" INTEGER,
    "hardship_type" TEXT,
    "hardship_reason" VARCHAR(255),
    "hardship_status" TEXT,
    "deferral_term" NUMBER(8,0),
    "hardship_amount" FLOAT,
    "hardship_start_date" TIMESTAMP,
    "hardship_end_date" TIMESTAMP,
    "payment_plan_start_date" TIMESTAMP,
    "hardship_length" NUMBER(8,0),
    "hardship_dpd" FLOAT,
    "hardship_loan_status" TEXT,
    "orig_projected_additional_accrued_interest" FLOAT,
    "hardship_payoff_balance_amount" FLOAT,
    "hardship_last_payment_amount" FLOAT,
    "created_on" TIMESTAMP, -- This should be pulled from the data
    "last_updated" TIMESTAMP, -- This should be pulled from the data
    "warehouse_created_on" TIMESTAMP DEFAULT current_timestamp(),
    "warehouse_last_updated" TIMESTAMP DEFAULT current_timestamp(),
    CONSTRAINT hardship_fk 
        FOREIGN KEY("loan_id") 
        REFERENCES "ACCEPTED"("id")
);
CREATE TABLE PUBLIC."SETTLEMENT" (
    "loan_id" INTEGER,
    "debt_settlement_flag_date" TIMESTAMP,
    "settlement_status" TEXT,
    "settlement_date" TIMESTAMP,
    "settlement_amount" FLOAT,
    "settlement_percentage" FLOAT,
    "settlement_term" NUMBER(8,0),
    "created_on" TIMESTAMP, -- This should be pulled from the data
    "last_updated" TIMESTAMP, -- This should be pulled from the data
    "warehouse_created_on" TIMESTAMP DEFAULT current_timestamp(),
    "warehouse_last_updated" TIMESTAMP DEFAULT current_timestamp(),
    CONSTRAINT hardship_fk 
        FOREIGN KEY("loan_id") 
        REFERENCES "ACCEPTED"("id")
);

-- Reconstructed table view
CREATE  OR REPLACE VIEW whole_table AS
  select ACCEPTED.*, S.*, H.*
    from ACCEPTED
       LEFT OUTER JOIN (SELECT "loan_id", "debt_settlement_flag_date", "settlement_status", "settlement_date", "settlement_amount",  "settlement_percentage", "settlement_term" FROM SETTLEMENT) AS S ON(S."loan_id" = ACCEPTED."id")
       LEFT OUTER JOIN (SELECT "loan_id","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount" FROM HARDSHIP) AS H ON(H."loan_id" = ACCEPTED."id");